// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/icbfs/v1/block.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EntryType mirrors internal/block.EntryType.
type EntryType int32

const (
	EntryType_ENTRY_TYPE_FILE    EntryType = 0
	EntryType_ENTRY_TYPE_DIR     EntryType = 1
	EntryType_ENTRY_TYPE_SYMLINK EntryType = 2
)

// Enum value maps for EntryType.
var (
	EntryType_name = map[int32]string{
		0: "ENTRY_TYPE_FILE",
		1: "ENTRY_TYPE_DIR",
		2: "ENTRY_TYPE_SYMLINK",
	}
	EntryType_value = map[string]int32{
		"ENTRY_TYPE_FILE":    0,
		"ENTRY_TYPE_DIR":     1,
		"ENTRY_TYPE_SYMLINK": 2,
	}
)

func (x EntryType) Enum() *EntryType {
	p := new(EntryType)
	*p = x
	return p
}

func (x EntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_icbfs_v1_block_proto_enumTypes[0].Descriptor()
}

func (EntryType) Type() protoreflect.EnumType {
	return &file_proto_icbfs_v1_block_proto_enumTypes[0]
}

func (x EntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryType.Descriptor instead.
func (EntryType) EnumDescriptor() ([]byte, []int) {
	return file_proto_icbfs_v1_block_proto_rawDescGZIP(), []int{0}
}

// BlockKind mirrors internal/block.Kind.
type BlockKind int32

const (
	BlockKind_BLOCK_KIND_LEAF     BlockKind = 0
	BlockKind_BLOCK_KIND_INTERNAL BlockKind = 1
)

// Enum value maps for BlockKind.
var (
	BlockKind_name = map[int32]string{
		0: "BLOCK_KIND_LEAF",
		1: "BLOCK_KIND_INTERNAL",
	}
	BlockKind_value = map[string]int32{
		"BLOCK_KIND_LEAF":     0,
		"BLOCK_KIND_INTERNAL": 1,
	}
)

func (x BlockKind) Enum() *BlockKind {
	p := new(BlockKind)
	*p = x
	return p
}

func (x BlockKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BlockKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_icbfs_v1_block_proto_enumTypes[1].Descriptor()
}

func (BlockKind) Type() protoreflect.EnumType {
	return &file_proto_icbfs_v1_block_proto_enumTypes[1]
}

func (x BlockKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BlockKind.Descriptor instead.
func (BlockKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_icbfs_v1_block_proto_rawDescGZIP(), []int{1}
}

// Entry is one row of a leaf block: a name -> UUID mapping.
type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Type          EntryType              `protobuf:"varint,3,opt,name=type,proto3,enum=icbfs.v1.EntryType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_proto_icbfs_v1_block_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_icbfs_v1_block_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_proto_icbfs_v1_block_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Entry) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Entry) GetType() EntryType {
	if x != nil {
		return x.Type
	}
	return EntryType_ENTRY_TYPE_FILE
}

// Child is one range pointer in an internal node.
type Child struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinKey        string                 `protobuf:"bytes,1,opt,name=min_key,json=minKey,proto3" json:"min_key,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Child) Reset() {
	*x = Child{}
	mi := &file_proto_icbfs_v1_block_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Child) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Child) ProtoMessage() {}

func (x *Child) ProtoReflect() protoreflect.Message {
	mi := &file_proto_icbfs_v1_block_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Child.ProtoReflect.Descriptor instead.
func (*Child) Descriptor() ([]byte, []int) {
	return file_proto_icbfs_v1_block_proto_rawDescGZIP(), []int{1}
}

func (x *Child) GetMinKey() string {
	if x != nil {
		return x.MinKey
	}
	return ""
}

func (x *Child) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// Block is the wire representation of internal/block.Block: either a
// Leaf (entries populated) or an Internal node (children populated).
type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          BlockKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=icbfs.v1.BlockKind" json:"kind,omitempty"`
	Entries       []*Entry               `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	Children      []*Child               `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_proto_icbfs_v1_block_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_proto_icbfs_v1_block_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_proto_icbfs_v1_block_proto_rawDescGZIP(), []int{2}
}

func (x *Block) GetKind() BlockKind {
	if x != nil {
		return x.Kind
	}
	return BlockKind_BLOCK_KIND_LEAF
}

func (x *Block) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *Block) GetChildren() []*Child {
	if x != nil {
		return x.Children
	}
	return nil
}

var File_proto_icbfs_v1_block_proto protoreflect.FileDescriptor

const file_proto_icbfs_v1_block_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/icbfs/v1/block.proto\x12\bicbfs.v1\"X\n" +
	"\x05Entry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12'\n" +
	"\x04type\x18\x03 \x01(\x0e2\x13.icbfs.v1.EntryTypeR\x04type\"4\n" +
	"\x05Child\x12\x17\n" +
	"\amin_key\x18\x01 \x01(\tR\x06minKey\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\"\x88\x01\n" +
	"\x05Block\x12'\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x13.icbfs.v1.BlockKindR\x04kind\x12)\n" +
	"\aentries\x18\x02 \x03(\v2\x0f.icbfs.v1.EntryR\aentries\x12+\n" +
	"\bchildren\x18\x03 \x03(\v2\x0f.icbfs.v1.ChildR\bchildren*L\n" +
	"\tEntryType\x12\x13\n" +
	"\x0fENTRY_TYPE_FILE\x10\x00\x12\x12\n" +
	"\x0eENTRY_TYPE_DIR\x10\x01\x12\x16\n" +
	"\x12ENTRY_TYPE_SYMLINK\x10\x02*9\n" +
	"\tBlockKind\x12\x13\n" +
	"\x0fBLOCK_KIND_LEAF\x10\x00\x12\x17\n" +
	"\x13BLOCK_KIND_INTERNAL\x10\x01B+Z)github.com/resurgentech/icbfs/internal/pbb\x06proto3"

var (
	file_proto_icbfs_v1_block_proto_rawDescOnce sync.Once
	file_proto_icbfs_v1_block_proto_rawDescData []byte
)

func file_proto_icbfs_v1_block_proto_rawDescGZIP() []byte {
	file_proto_icbfs_v1_block_proto_rawDescOnce.Do(func() {
		file_proto_icbfs_v1_block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_icbfs_v1_block_proto_rawDesc), len(file_proto_icbfs_v1_block_proto_rawDesc)))
	})
	return file_proto_icbfs_v1_block_proto_rawDescData
}

var file_proto_icbfs_v1_block_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_icbfs_v1_block_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_icbfs_v1_block_proto_goTypes = []any{
	(EntryType)(0), // 0: icbfs.v1.EntryType
	(BlockKind)(0), // 1: icbfs.v1.BlockKind
	(*Entry)(nil),  // 2: icbfs.v1.Entry
	(*Child)(nil),  // 3: icbfs.v1.Child
	(*Block)(nil),  // 4: icbfs.v1.Block
}
var file_proto_icbfs_v1_block_proto_depIdxs = []int32{
	0, // 0: icbfs.v1.Entry.type:type_name -> icbfs.v1.EntryType
	1, // 1: icbfs.v1.Block.kind:type_name -> icbfs.v1.BlockKind
	2, // 2: icbfs.v1.Block.entries:type_name -> icbfs.v1.Entry
	3, // 3: icbfs.v1.Block.children:type_name -> icbfs.v1.Child
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_icbfs_v1_block_proto_init() }
func file_proto_icbfs_v1_block_proto_init() {
	if File_proto_icbfs_v1_block_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_icbfs_v1_block_proto_rawDesc), len(file_proto_icbfs_v1_block_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_icbfs_v1_block_proto_goTypes,
		DependencyIndexes: file_proto_icbfs_v1_block_proto_depIdxs,
		EnumInfos:         file_proto_icbfs_v1_block_proto_enumTypes,
		MessageInfos:      file_proto_icbfs_v1_block_proto_msgTypes,
	}.Build()
	File_proto_icbfs_v1_block_proto = out.File
	file_proto_icbfs_v1_block_proto_goTypes = nil
	file_proto_icbfs_v1_block_proto_depIdxs = nil
}
