// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/icbfs/v1/lock.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lock is the whole-file lock object body — see ARCHITECTURE.md's
// Locking section and ROADMAP.md's task B2. Generalized to a list of
// byte-range entries in task B4; this message covers whole-file only.
type Lock struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Holder          string                 `protobuf:"bytes,1,opt,name=holder,proto3" json:"holder,omitempty"`
	ExpiresAtUnixMs int64                  `protobuf:"varint,2,opt,name=expires_at_unix_ms,json=expiresAtUnixMs,proto3" json:"expires_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Lock) Reset() {
	*x = Lock{}
	mi := &file_proto_icbfs_v1_lock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lock) ProtoMessage() {}

func (x *Lock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_icbfs_v1_lock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lock.ProtoReflect.Descriptor instead.
func (*Lock) Descriptor() ([]byte, []int) {
	return file_proto_icbfs_v1_lock_proto_rawDescGZIP(), []int{0}
}

func (x *Lock) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

func (x *Lock) GetExpiresAtUnixMs() int64 {
	if x != nil {
		return x.ExpiresAtUnixMs
	}
	return 0
}

var File_proto_icbfs_v1_lock_proto protoreflect.FileDescriptor

const file_proto_icbfs_v1_lock_proto_rawDesc = "" +
	"\n" +
	"\x19proto/icbfs/v1/lock.proto\x12\bicbfs.v1\"K\n" +
	"\x04Lock\x12\x16\n" +
	"\x06holder\x18\x01 \x01(\tR\x06holder\x12+\n" +
	"\x12expires_at_unix_ms\x18\x02 \x01(\x03R\x0fexpiresAtUnixMsB+Z)github.com/resurgentech/icbfs/internal/pbb\x06proto3"

var (
	file_proto_icbfs_v1_lock_proto_rawDescOnce sync.Once
	file_proto_icbfs_v1_lock_proto_rawDescData []byte
)

func file_proto_icbfs_v1_lock_proto_rawDescGZIP() []byte {
	file_proto_icbfs_v1_lock_proto_rawDescOnce.Do(func() {
		file_proto_icbfs_v1_lock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_icbfs_v1_lock_proto_rawDesc), len(file_proto_icbfs_v1_lock_proto_rawDesc)))
	})
	return file_proto_icbfs_v1_lock_proto_rawDescData
}

var file_proto_icbfs_v1_lock_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_icbfs_v1_lock_proto_goTypes = []any{
	(*Lock)(nil), // 0: icbfs.v1.Lock
}
var file_proto_icbfs_v1_lock_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_icbfs_v1_lock_proto_init() }
func file_proto_icbfs_v1_lock_proto_init() {
	if File_proto_icbfs_v1_lock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_icbfs_v1_lock_proto_rawDesc), len(file_proto_icbfs_v1_lock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_icbfs_v1_lock_proto_goTypes,
		DependencyIndexes: file_proto_icbfs_v1_lock_proto_depIdxs,
		MessageInfos:      file_proto_icbfs_v1_lock_proto_msgTypes,
	}.Build()
	File_proto_icbfs_v1_lock_proto = out.File
	file_proto_icbfs_v1_lock_proto_goTypes = nil
	file_proto_icbfs_v1_lock_proto_depIdxs = nil
}
