// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: spec/proto/icbfs/v1/master.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FilesystemEntry is one slot in the MasterBlock's list. An empty Name
// means this slot is free, available for reuse by a later Create — see
// ARCHITECTURE.md's Multiple filesystems per bucket section. A
// filesystem's ID is its position (index) in MasterBlock.filesystems,
// not a field stored here at all.
type FilesystemEntry struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Name     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size     uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Archived bool                   `protobuf:"varint,3,opt,name=archived,proto3" json:"archived,omitempty"`
	// primary_windows: set once at creation, immutable afterward — see
	// ARCHITECTURE.md's "Windows compatibility: primary mode" section
	// and ROADMAP.md's Part F, task F5. false (the default) means
	// primary-POSIX.
	PrimaryWindows bool `protobuf:"varint,4,opt,name=primary_windows,json=primaryWindows,proto3" json:"primary_windows,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FilesystemEntry) Reset() {
	*x = FilesystemEntry{}
	mi := &file_spec_proto_icbfs_v1_master_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesystemEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesystemEntry) ProtoMessage() {}

func (x *FilesystemEntry) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_icbfs_v1_master_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesystemEntry.ProtoReflect.Descriptor instead.
func (*FilesystemEntry) Descriptor() ([]byte, []int) {
	return file_spec_proto_icbfs_v1_master_proto_rawDescGZIP(), []int{0}
}

func (x *FilesystemEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FilesystemEntry) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FilesystemEntry) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

func (x *FilesystemEntry) GetPrimaryWindows() bool {
	if x != nil {
		return x.PrimaryWindows
	}
	return false
}

// MasterBlock is the body of the one, fixed, well-known master-block
// object per bucket. The list can only ever grow in length, never
// shrink or reorder — a deleted filesystem's entry is blanked in place
// (Name = ""), not removed, since removing it would shift every later
// entry's position, and therefore its ID, out from under objects that
// are already permanently keyed with the old one.
type MasterBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filesystems   []*FilesystemEntry     `protobuf:"bytes,1,rep,name=filesystems,proto3" json:"filesystems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MasterBlock) Reset() {
	*x = MasterBlock{}
	mi := &file_spec_proto_icbfs_v1_master_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MasterBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterBlock) ProtoMessage() {}

func (x *MasterBlock) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_icbfs_v1_master_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterBlock.ProtoReflect.Descriptor instead.
func (*MasterBlock) Descriptor() ([]byte, []int) {
	return file_spec_proto_icbfs_v1_master_proto_rawDescGZIP(), []int{1}
}

func (x *MasterBlock) GetFilesystems() []*FilesystemEntry {
	if x != nil {
		return x.Filesystems
	}
	return nil
}

var File_spec_proto_icbfs_v1_master_proto protoreflect.FileDescriptor

const file_spec_proto_icbfs_v1_master_proto_rawDesc = "" +
	"\n" +
	" spec/proto/icbfs/v1/master.proto\x12\bicbfs.v1\"~\n" +
	"\x0fFilesystemEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12\x1a\n" +
	"\barchived\x18\x03 \x01(\bR\barchived\x12'\n" +
	"\x0fprimary_windows\x18\x04 \x01(\bR\x0eprimaryWindows\"J\n" +
	"\vMasterBlock\x12;\n" +
	"\vfilesystems\x18\x01 \x03(\v2\x19.icbfs.v1.FilesystemEntryR\vfilesystemsB+Z)github.com/resurgentech/icbfs/internal/pbb\x06proto3"

var (
	file_spec_proto_icbfs_v1_master_proto_rawDescOnce sync.Once
	file_spec_proto_icbfs_v1_master_proto_rawDescData []byte
)

func file_spec_proto_icbfs_v1_master_proto_rawDescGZIP() []byte {
	file_spec_proto_icbfs_v1_master_proto_rawDescOnce.Do(func() {
		file_spec_proto_icbfs_v1_master_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spec_proto_icbfs_v1_master_proto_rawDesc), len(file_spec_proto_icbfs_v1_master_proto_rawDesc)))
	})
	return file_spec_proto_icbfs_v1_master_proto_rawDescData
}

var file_spec_proto_icbfs_v1_master_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_spec_proto_icbfs_v1_master_proto_goTypes = []any{
	(*FilesystemEntry)(nil), // 0: icbfs.v1.FilesystemEntry
	(*MasterBlock)(nil),     // 1: icbfs.v1.MasterBlock
}
var file_spec_proto_icbfs_v1_master_proto_depIdxs = []int32{
	0, // 0: icbfs.v1.MasterBlock.filesystems:type_name -> icbfs.v1.FilesystemEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_spec_proto_icbfs_v1_master_proto_init() }
func file_spec_proto_icbfs_v1_master_proto_init() {
	if File_spec_proto_icbfs_v1_master_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spec_proto_icbfs_v1_master_proto_rawDesc), len(file_spec_proto_icbfs_v1_master_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spec_proto_icbfs_v1_master_proto_goTypes,
		DependencyIndexes: file_spec_proto_icbfs_v1_master_proto_depIdxs,
		MessageInfos:      file_spec_proto_icbfs_v1_master_proto_msgTypes,
	}.Build()
	File_spec_proto_icbfs_v1_master_proto = out.File
	file_spec_proto_icbfs_v1_master_proto_goTypes = nil
	file_spec_proto_icbfs_v1_master_proto_depIdxs = nil
}
