// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/icbfs/v1/metadata.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Metadata is the body of a file/symlink's dedicated <uuid>.metadata
// object — see ARCHITECTURE.md's Metadata model section. mode/uid/gid/
// nlink live here, as does xattrs, a generic name -> bytes map covering
// POSIX ACLs (under the well-known key "system.posix_acl_access",
// exactly mirroring Linux's own xattr-based ACL representation), future
// Windows ACLs (under "windows.acl"), and ordinary user xattrs — all
// just named entries, with no special-casing at the storage layer.
//
// Directories do not get one of these; they aren't hard-linkable, so
// their mode/uid/gid stay in native object metadata on the directory
// block object itself (see internal/icbfs/attr.go).
type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          uint32                 `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Uid           uint32                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint32                 `protobuf:"varint,3,opt,name=gid,proto3" json:"gid,omitempty"`
	Nlink         uint32                 `protobuf:"varint,4,opt,name=nlink,proto3" json:"nlink,omitempty"`
	Xattrs        map[string][]byte      `protobuf:"bytes,5,rep,name=xattrs,proto3" json:"xattrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_proto_icbfs_v1_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_icbfs_v1_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_proto_icbfs_v1_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *Metadata) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Metadata) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *Metadata) GetNlink() uint32 {
	if x != nil {
		return x.Nlink
	}
	return 0
}

func (x *Metadata) GetXattrs() map[string][]byte {
	if x != nil {
		return x.Xattrs
	}
	return nil
}

var File_proto_icbfs_v1_metadata_proto protoreflect.FileDescriptor

const file_proto_icbfs_v1_metadata_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/icbfs/v1/metadata.proto\x12\bicbfs.v1\"\xcb\x01\n" +
	"\bMetadata\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\rR\x04mode\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\x03 \x01(\rR\x03gid\x12\x14\n" +
	"\x05nlink\x18\x04 \x01(\rR\x05nlink\x126\n" +
	"\x06xattrs\x18\x05 \x03(\v2\x1e.icbfs.v1.Metadata.XattrsEntryR\x06xattrs\x1a9\n" +
	"\vXattrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01B+Z)github.com/resurgentech/icbfs/internal/pbb\x06proto3"

var (
	file_proto_icbfs_v1_metadata_proto_rawDescOnce sync.Once
	file_proto_icbfs_v1_metadata_proto_rawDescData []byte
)

func file_proto_icbfs_v1_metadata_proto_rawDescGZIP() []byte {
	file_proto_icbfs_v1_metadata_proto_rawDescOnce.Do(func() {
		file_proto_icbfs_v1_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_icbfs_v1_metadata_proto_rawDesc), len(file_proto_icbfs_v1_metadata_proto_rawDesc)))
	})
	return file_proto_icbfs_v1_metadata_proto_rawDescData
}

var file_proto_icbfs_v1_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_icbfs_v1_metadata_proto_goTypes = []any{
	(*Metadata)(nil), // 0: icbfs.v1.Metadata
	nil,              // 1: icbfs.v1.Metadata.XattrsEntry
}
var file_proto_icbfs_v1_metadata_proto_depIdxs = []int32{
	1, // 0: icbfs.v1.Metadata.xattrs:type_name -> icbfs.v1.Metadata.XattrsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_icbfs_v1_metadata_proto_init() }
func file_proto_icbfs_v1_metadata_proto_init() {
	if File_proto_icbfs_v1_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_icbfs_v1_metadata_proto_rawDesc), len(file_proto_icbfs_v1_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_icbfs_v1_metadata_proto_goTypes,
		DependencyIndexes: file_proto_icbfs_v1_metadata_proto_depIdxs,
		MessageInfos:      file_proto_icbfs_v1_metadata_proto_msgTypes,
	}.Build()
	File_proto_icbfs_v1_metadata_proto = out.File
	file_proto_icbfs_v1_metadata_proto_goTypes = nil
	file_proto_icbfs_v1_metadata_proto_depIdxs = nil
}
